### ISSUE TITLE
WFP output ?

### ISSUE THREAD

**Issue by antagomir** [reptalex/WrightFisher#3]
The WFP function gives the timesteps x species matrix as its second output:
set.seed(2)
wfp <- WFP(nSpecies=15, lambda=25)

I noticed that at each timestep (row) the species abundances sum up to one, but only approximately. Is this intentional, or a bug - It seems to me that the output should be relative abundances that always sum up to one exactly ?

**Comment by reptalex** [comment]
Hi Leo!

There is some numerical instability in simulating the WFP. For the time being. Numerical integration of stochastic differential equations on bounded domains such as the simplex risks hopping out of bounds (an especially pernicious problems for simplexes with large nSpecies, e.g. nSpecies>2). The method I've used allows for fairly reliable simulation of high-dimensional Wright-Fisher diffusion processes without needing to add a bunch of conditions for if we hop out-of-bounds or if we're close to the bounds. However, the cons of my method is that, while species' abundances rarely go negative, the community size is not preserved perfectly. For more details on this method - it could use some critical feedback / peer-review - check out my thesis "Competition and Coexistence in an Unpredictable World" (it should be freely available).

To allow the user can see the extent of numerical instability in their simulation and contemplate using a smaller input for "dt", I don't want to mask that numerical instability by correcting the default output to sum to 1. If you're using a sensitive down-stream algorithm that requires relative abundances sum to 1, feel free to correct via:

R <- wfp[[2]]
R <- R/rowSums(R)

**Comment by antagomir** [comment]
Ok I understand and sounds fine. I can do that.

Leo

**Comment by reptalex** [comment]
The new method for simulating the WFP utilizes the volatility-stabilized market model. Simulations of the VSM are in the postiive orthant, and are then projected on to the simplex to ensure that the output, X$Community, is a matrix of relative abundances (rows are timepoints and columns are species).
